# Generated by Django 3.2.6 on 2021-12-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20211222_0315'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchases',
            field=models.ManyToManyField(null=True, related_name='purchases', to='login_app.User'),
        ),
    ]
