# Generated by Django 3.2.6 on 2021-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20211222_0315'),
        ('marketplace', '0004_user_item_count'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='item',
        #     name='purchases',
        #     field=models.ManyToManyField(related_name='purchases', through='marketplace.User_Item_Count', to='login_app.User'),
        # ),
        migrations.RemoveField(
            model_name='item',
            name='purchases',
        ),
        migrations.AddField(
            model_name='item',
            name='purchases',
            field=models.ManyToManyField(related_name='purchases', through='marketplace.User_Item_Count', to='login_app.User')
        )
    ]
