# Generated by Django 3.2.6 on 2021-12-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_item_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_item_count',
            old_name='count',
            new_name='orders',
        ),
    ]
