# Generated by Django 3.2.6 on 2021-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20211222_0315'),
        ('marketplace', '0006_rename_count_user_item_count_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchases',
            field=models.ManyToManyField(through='marketplace.User_Item_Count', to='login_app.User'),
        ),
    ]
