# Generated by Django 3.2.6 on 2022-02-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_category_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
