# Generated by Django 2.2 on 2022-02-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_cart_item_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_Item_Count',
        ),
    ]
