# Generated by Django 2.2 on 2022-02-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20220213_2301'),
        ('marketplace', '0016_delete_cart_item_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Item_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ManyToManyField(related_name='carts', to='marketplace.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
    ]
