# Generated by Django 2.2 on 2022-02-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20220213_2301'),
        ('marketplace', '0017_cart_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item_count',
            name='user',
        ),
        migrations.AddField(
            model_name='cart_item_count',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.RemoveField(
            model_name='cart_item_count',
            name='item',
        ),
        migrations.AddField(
            model_name='cart_item_count',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Item'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='cart_item_count',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Cart'),
        ),
        migrations.AddField(
            model_name='item',
            name='carts',
            field=models.ManyToManyField(through='marketplace.Cart_Item_Count', to='marketplace.Cart'),
        ),
    ]
